/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.amf.registration.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CustomUser service. Represents a row in the &quot;AMFRegistration_CustomUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.amf.registration.model.impl.CustomUserModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.amf.registration.model.impl.CustomUserImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CustomUser
 * @generated
 */
@ProviderType
public interface CustomUserModel
	extends BaseModel<CustomUser>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a custom user model instance should use the {@link CustomUser} interface instead.
	 */

	/**
	 * Returns the primary key of this custom user.
	 *
	 * @return the primary key of this custom user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this custom user.
	 *
	 * @param primaryKey the primary key of this custom user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the custom user ID of this custom user.
	 *
	 * @return the custom user ID of this custom user
	 */
	public long getCustomUserId();

	/**
	 * Sets the custom user ID of this custom user.
	 *
	 * @param customUserId the custom user ID of this custom user
	 */
	public void setCustomUserId(long customUserId);

	/**
	 * Returns the custom user uuid of this custom user.
	 *
	 * @return the custom user uuid of this custom user
	 */
	public String getCustomUserUuid();

	/**
	 * Sets the custom user uuid of this custom user.
	 *
	 * @param customUserUuid the custom user uuid of this custom user
	 */
	public void setCustomUserUuid(String customUserUuid);

	/**
	 * Returns the group ID of this custom user.
	 *
	 * @return the group ID of this custom user
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this custom user.
	 *
	 * @param groupId the group ID of this custom user
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this custom user.
	 *
	 * @return the company ID of this custom user
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this custom user.
	 *
	 * @param companyId the company ID of this custom user
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this custom user.
	 *
	 * @return the user ID of this custom user
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this custom user.
	 *
	 * @param userId the user ID of this custom user
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this custom user.
	 *
	 * @return the user uuid of this custom user
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this custom user.
	 *
	 * @param userUuid the user uuid of this custom user
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this custom user.
	 *
	 * @return the user name of this custom user
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this custom user.
	 *
	 * @param userName the user name of this custom user
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this custom user.
	 *
	 * @return the create date of this custom user
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this custom user.
	 *
	 * @param createDate the create date of this custom user
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this custom user.
	 *
	 * @return the modified date of this custom user
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this custom user.
	 *
	 * @param modifiedDate the modified date of this custom user
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the home_phone of this custom user.
	 *
	 * @return the home_phone of this custom user
	 */
	@AutoEscape
	public String getHome_phone();

	/**
	 * Sets the home_phone of this custom user.
	 *
	 * @param home_phone the home_phone of this custom user
	 */
	public void setHome_phone(String home_phone);

	/**
	 * Returns the mobile_phone of this custom user.
	 *
	 * @return the mobile_phone of this custom user
	 */
	@AutoEscape
	public String getMobile_phone();

	/**
	 * Sets the mobile_phone of this custom user.
	 *
	 * @param mobile_phone the mobile_phone of this custom user
	 */
	public void setMobile_phone(String mobile_phone);

	/**
	 * Returns the state of this custom user.
	 *
	 * @return the state of this custom user
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this custom user.
	 *
	 * @param state the state of this custom user
	 */
	public void setState(String state);

	/**
	 * Returns the security_question of this custom user.
	 *
	 * @return the security_question of this custom user
	 */
	@AutoEscape
	public String getSecurity_question();

	/**
	 * Sets the security_question of this custom user.
	 *
	 * @param security_question the security_question of this custom user
	 */
	public void setSecurity_question(String security_question);

	/**
	 * Returns the security_answer of this custom user.
	 *
	 * @return the security_answer of this custom user
	 */
	@AutoEscape
	public String getSecurity_answer();

	/**
	 * Sets the security_answer of this custom user.
	 *
	 * @param security_answer the security_answer of this custom user
	 */
	public void setSecurity_answer(String security_answer);

	/**
	 * Returns the accepted_tou of this custom user.
	 *
	 * @return the accepted_tou of this custom user
	 */
	public boolean getAccepted_tou();

	/**
	 * Returns <code>true</code> if this custom user is accepted_tou.
	 *
	 * @return <code>true</code> if this custom user is accepted_tou; <code>false</code> otherwise
	 */
	public boolean isAccepted_tou();

	/**
	 * Sets whether this custom user is accepted_tou.
	 *
	 * @param accepted_tou the accepted_tou of this custom user
	 */
	public void setAccepted_tou(boolean accepted_tou);

}